### PR TITLE
Necessary changes to upgrade the library to latest Kafka version

### PR DESCRIPTION
**Pull request by kasuri**
The changes are backward compatible.

### CODE REVIEW

**Comment by Crim** [comment]
First....thanks for the contribution!  Much appreciated!

Do you think we should make the kafka dependency scoped to provided?  Does that get us anything in terms of not forcing a Kafka version on people using the library?  There are a couple things I want to validate with this:

- Is there a way to support multiple versions of Kafka for people still using older versions in their projects?
- How should we adjust the version for the library based on the change?
- Need to update the README/CHANGELOG.

**Comment by kasuri** [comment]
The version change that I made in pom.xml was not necessary and can be reverted.  I only did that to bring the project to latest library.  

Yes, I think it's a good idea to make the Kafka dependncy scoped to provided to let others provide their own Kafka version.  Another way people can use any Kafka version of their choice is by putting an exclusion for Kafka when they specify dependency for Kafka-JUnit.

Version-wise, it think it's just a minor version and you might make it 2.1.0 perhaps. 

"Need to update the README/CHANGELOG - Does that need to happen now or after the PR is merged?  Do we just want to update to reflect the change?

Thanks

**Comment by Crim** [comment]
Sounds good.  Lets do this then... Can you revert this line in the pom:

```xml
<kafkaVersion>1.1.0</kafkaVersion>
```
And mark

And I'll update README/Changelog with some notes about how to use it with different versions

**Comment by kasuri** [comment]
Will create a new PR after changes in pom.xml

**Pull request closed without merging**
